# resources section for defining resources
resources:
- name: repo
  type: git
  source: 
    uri: https://github.com/markwillis75/concourse-examples
    

jobs:
  - name: hello-world-job
    plan: 
    - get: repo     # link this job to the repo
      trigger: true # trigger this job whenever new versions are emitted
    - task: hello-world-task
      config:
        platform: linux
        image_resource: 
          type: registry-image
          source: 
            repository: busybox
        run:
          path: echo
          args: ["Hello World!"]