jobs:
  - name: hello-world-job
    plan: 
    - task: output-task
      config:
        platform: linux
        image_resource: 
          type: registry-image
          source: 
            repository: busybox
        outputs:
        - name: the-artifact
        run:
          path: sh
          args:
          - -cx
          - |
            ls -l .
            echo "hello from another step!" > the-artifact/message
    - task: input-task
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: busybox
        # must declare the input in order to use it
        inputs:
        - name: the-artifact
        run:
          path: sh
          args:
          - -cx
          - |
            ls -l .
            cat the-artifact/message